require: rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false